models:
  # - name: "BLAST"
  #   model_info:
  #     model_name: "BLAST"
  #     sequential: false
  #   features:
  #     - name: "PROTEINSEQ" # only option for blast
  - name: "Baseline Model - Logistic Regression"
    model_info:
      model_name: "LOGREG"
      sequential: false
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "AAC"
      - name: "ATC"
      - name: "CTD"
      - name: "PCP"
  - name: "PhageScanner (RNN)"
    model_info:
      model_name: "RNN"
      sequential: 3
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0
classes:
  - name: Lysin # No spaces. Can differ between pipelines.
    final_csv: "lysin_database/lysins_Lysin.csv" # local path.
  - name: non-Lysin
    final_csv: "lysin_database/lysins_non-Lysin.csv"
