clustering:
  deduplication-threshold: 100
  clustering-percentage: 90
  k_partitions: 5 # number of partitions in k-fold cross validation
classes:
  - name: PVP
    uniprot: "capsid AND cc_subcellular_location: virion AND reviewed: true"
    entrez: "bacteriophage[Organism] AND ((shaft[Title] OR sheath[Title]) AND tail[Title]) OR head-tail[Title] OR tail fiber[Title] OR portal[Title] OR minor tail[Title] OR major tail[Title] OR baseplate[Title] OR minor capsid[Title] OR major capsid[Title])"
  - name: non-PVP
    uniprot: "capsid NOT cc_subcellular_location: virion AND reviewed: true"
    entrez: "bacteriophage[Organism] NOT (bacteriophage[Organism] AND ((shaft[Title] OR sheath[Title]) AND tail[Title]) OR head-tail[Title] OR tail fiber[Title] OR portal[Title] OR minor tail[Title] OR major tail[Title] OR baseplate[Title] OR minor capsid[Title] OR major capsid[Title]))"
models:
  # - name: "BLAST"
  #   model_info:
  #     model_name: "BLAST"
  #     sequential: false
  #   features:
  #     - name: "PROTEINSEQ" # only option for blast
  # - name: "iVIREONS (FFNN)"
  #   model_info:
  #     model_name: "FFNN"
  #     sequential: false
  #   features:
  #     - name: "AAC"
  #     - name: "ISO"
  # - name: "Feng et al. (Naive Bayes)"
  #   model_info:
  #     model_name: "MULTINAIVEBAYES"
  #     sequential: false
  #   features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
  #     - name: "AAC"
  #     - name: "DPC"
  #       parameters:
  #         gap_size: 0
  - name: "PVP-SVM (SVM)"
    model_info:
      model_name: "SVM"
      sequential: false
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0
      - name: "AAC"
      - name: "ATC"
      - name: "CTD"
      - name: "PCP"
  # - name: "SCORPION-partial (RF)"
  #   model_info:
  #     model_name: "RANDOMFOREST"
  #     sequential: false
  #   features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
  #     - name: "AAC"
  #     - name: "CTD"
  #     - name: "DPC"
  #       parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
  #         gap_size: 0
  # - name: "Baseline Model - Logistic Regression"
  #   model_info:
  #     model_name: "LOGREG"
  #     sequential: false
  #   features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
  #     - name: "AAC"
  #     - name: "ATC"
  #     - name: "CTD"
  #     - name: "PCP"
  - name: "PhageScanner (RNN)"
    model_info:
      model_name: "RNN"
      sequential: 3
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0
  - name: "DeePVP (CNN)"
    model_info:
      model_name: "CNN"
      sequential: false
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "SEQUENTIALONEHOT"