clustering:
  clustering-percentage: 90
  k_partitions: 5 # number of partitions in k-fold cross validation
  deduplication-threshold: 100
classes:
  - name: MajorCapsid
    uniprot: "major capsid AND cc_subcellular_location: virion AND reviewed: true"
    # entrez: "major capsid[Title]"
  - name: MinorCapsid
    uniprot: "minor capsid AND cc_subcellular_location: virion AND reviewed: true"
    # entrez: "minor capsid[Title]"
  - name: Baseplate
    uniprot: "baseplate AND cc_subcellular_location: virion AND reviewed: true"
    # entrez: "baseplate[Title]"
  - name: MajorTail
    uniprot: "major tail AND cc_subcellular_location: virion AND reviewed: true"
    # entrez: "major tail[Title]"
  - name: MinorTail
    uniprot: "minor tail AND cc_subcellular_location: virion AND reviewed: true"
    # entrez: "minor tail[Title]"
  - name: Portal
    uniprot: "portal AND cc_subcellular_location: virion AND reviewed: true"
    # entrez: "portal[Title]"
  - name: TailFiber
    uniprot: "tail fiber AND cc_subcellular_location: virion AND reviewed: true"
    # entrez: "tail fiber[Title]"
  - name: Collar
    uniprot: "collar AND cc_subcellular_location: virion AND reviewed: true"
    # entrez: "collar[Title]"
  - name: shaft
    uniprot: "(shaft OR sheath) AND tail AND cc_subcellular_location: virion AND reviewed: true"
    # entrez: "(shaft[Title] OR sheath[Title]) AND tail[Title]"
  - name: HTJ
    uniprot: "head-tail AND cc_subcellular_location: virion AND reviewed: true"
    # entrez: "head-tail[Title]"
  - name: non-PVP
    uniprot: "capsid NOT cc_subcellular_location: virion AND reviewed: true"
    # entrez: "bacteriophage[Organism] NOT ((shaft[Title] OR sheath[Title]) AND tail[Title]) OR head-tail[Title] OR tail fiber[Title] OR portal[Title] OR minor tail[Title] OR major tail[Title] OR baseplate[Title] OR minor capsid[Title] OR major capsid[Title])"
models:
  - name: "FT-DPC (Logistic Regression)"
    model_info:
      model_name: "LOGREG"
      sequential: false
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0
  - name: "FT-DPC-g1 (Logistic Regression)"
    model_info:
      model_name: "LOGREG"
      sequential: false
    features:
      - name: "DPC"
        parameters:
          gap_size: 1
  - name: "FT-DPC-g9 (Logistic Regression)"
    model_info:
      model_name: "LOGREG"
      sequential: false
    features:
      - name: "DPC"
        parameters:
          gap_size: 9
  - name: "FT-TPC (Logistic Regression)"
    model_info:
      model_name: "LOGREG"
      sequential: false
    sequential: false
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "TPC"
  - name: "FT-AAC (Logistic Regression)"
    model_info:
      model_name: "LOGREG"
      sequential: false
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "AAC"
  - name: "FT-ISO (Logistic Regression)"
    model_info:
      model_name: "LOGREG"
      sequential: false
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "ISO"
  - name: "FT-ATC (Logistic Regression)"
    model_info:
      model_name: "LOGREG"
      sequential: false
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "ATC"
  - name: "FT-CTD (Logistic Regression)"
    model_info:
      model_name: "LOGREG"
      sequential: false
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "CTD"
  - name: "FT-CHEMFEATURES (Logistic Regression)"
    model_info:
      model_name: "LOGREG"
      sequential: false
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "CHEMFEATURES"
  - name: "FT-Mix1 (Logistic Regression)"
    model_info:
      model_name: "LOGREG"
      sequential: false
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "CHEMFEATURES"
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0
  - name: "FT-Mix2 (Logistic Regression)"
    model_info:
      model_name: "LOGREG"
      sequential: false
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0
      - name: "TPC"
  - name: "FT-Mix3 (Logistic Regression)"
    model_info:
      model_name: "LOGREG"
      sequential: false
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0
      - name: "ATC"
      - name: "CTD"
  - name: "FT-Mix4 (Logistic Regression)"
    model_info:
      model_name: "LOGREG"
      sequential: false
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "ATC"
      - name: "CTD"
      - name: "AAC"
      - name: "ISO"
      - name: "CHEMFEATURES"
