assembler: MEGAHIT
orffinder: PHANOTATE
models:
  - name: "binary PVP predictor"
    model_path: "binary_training_output/PVP-SVM (SVM)" # local path.
    index2class_file: "binary_training_output/index2class_name.csv" # local path.
    model_info:
      model_name: "SVM"
      sequential: false
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0
      - name: "AAC"
      - name: "ATC"
      - name: "CTD"
      - name: "PCP"
  - name: "multiclass PVP predictor"
    model_path: "training_output/PhANNs (FFNN)" # local path.
    index2class_file: "training_output/index2class_name.csv" # local path.
    model_info:
      model_name: "FFNN"
      sequential: false
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 2