assembler: MEGAHIT
orffinder: PHANOTATE
models:
  - name: "PVP predictor"
    model_path: "binary_training_output/PVP-SVM (SVM)" # local path.
    index2class_file: "binary_training_output/index2class_name.csv" # local path.
    model_info:
      model_name: "SVM"
    sequential: false
    features: # Use the same features used in training!
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0
  - name: "PhANNs (FFNN)"
    model_path: "training_output/PhANNs (FFNN)" # local path.
    index2class_file: "training_output/index2class_name.csv" # local path.
    model_info:
      model_name: "FFNN"
      is_sequential: false
    sequential: false
    class_balancing: false # Options: "downsample"
    feature_selection: false # Options:
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0