models:
  - name: "CNN TESTING"
    path: "model.pickle"
    model_info:
      model_name: "CNN"
      is_sequential: false
    sequential: false
    class_balancing: false # Options: "downsample"
    feature_selection: false # Options:
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0
  - name: "Baseline Classifier (Logistic Regression)"
    path: "model.pickle"
    model_info:
      model_name: "LOGREG"
      is_sequential: false
    sequential: false
    class_balancing: false # Options: "downsample"
    feature_selection: false # Options:
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0
classes:
  - name: PVP # No spaces. Can differ between pipelines.
    final_csv: "binary_database/binarydb_PVP.csv" # local path.
  - name: non-PVP
    final_csv: "binary_database/binarydb_non-PVP.csv"
