models:
  - name: "BLAST"
    model_info:
      model_name: "BLAST"
      is_sequential: false
    sequential: false
    class_balancing: false # Options: "downsample"
    feature_selection: false # Options:
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "PROTEINSEQ"
  - name: "Ru et al. (Random Forest)"
    model_info:
      model_name: "RANDOMFOREST"
      is_sequential: false
    sequential: false
    class_balancing: false # Options: "downsample"
    feature_selection: false # Options:
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0
  - name: "Testing.. (Gradient Boosting)"
    model_info:
      model_name: "GRADBOOST"
      is_sequential: false
    sequential: false
    class_balancing: false # Options: "downsample"
    feature_selection: false # Options:
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0
  - name: "PhagePred (Multinomial Naive Bayes)"
    model_info:
      model_name: "MULTINAIVEBAYES"
      is_sequential: false
    sequential: false
    class_balancing: false # Options: "downsample"
    feature_selection: false # Options:
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0
  - name: "PhANNs (FFNN)"
    model_info:
      model_name: "FFNN"
      is_sequential: false
    sequential: false
    class_balancing: false # Options: "downsample"
    feature_selection: false # Options:
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 2
      # - name: "ATC"
      # - name: "ISO"
      # - name: "CTD"
  - name: "PVP-SVM (SVM)"
    model_info:
      model_name: "SVM"
      is_sequential: false
    sequential: false
    class_balancing: false # Options: "downsample"
    feature_selection: false # Options:
    features: # Options: "AAC", "DPC", "ISO", "PSEUDOAAC", "ATC", "CTD"
      - name: "DPC"
        parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
          gap_size: 0
      # - name: "DPC"
      #   parameters: # DPC must have 'gap_size' parameter. 0 for regular DPC
      #     gap_size: 2
      # - name: "ATC"
      # - name: "ISO"
      # - name: "PSEUDOAAC"
      # - name: "CTD"
classes:
  - name: MajorCapsid # No spaces. Can differ between pipelines.
    final_csv: "benchmarking_database/benchmarking_MajorCapsid.csv" # local path.
  - name: MinorCapsid
    final_csv: "benchmarking_database/benchmarking_MinorCapsid.csv"
  - name: Baseplate
    final_csv: "benchmarking_database/benchmarking_Baseplate.csv"
  - name: MajorTail
    final_csv: "benchmarking_database/benchmarking_MajorTail.csv"
  - name: MinorTail
    final_csv: "benchmarking_database/benchmarking_MinorTail.csv"
  - name: Portal
    final_csv: "benchmarking_database/benchmarking_Portal.csv"
  - name: TailFiber
    final_csv: "benchmarking_database/benchmarking_TailFiber.csv"
  - name: Collar
    final_csv: "benchmarking_database/benchmarking_Collar.csv"
  - name: shaft
    final_csv: "benchmarking_database/benchmarking_shaft.csv"
  - name: HTJ
    final_csv: "benchmarking_database/benchmarking_HTJ.csv"
