name: phagescanner-cdci-actions

on:
    pull_request:
        branches:
            - master

jobs:
    mac-testing:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x' # Specify the Python version you need

            - name: Cache Python dependencies
              uses: actions/cache@v3
              with:
                  path: ~/Library/Caches/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: run unit tests for DNA module
              run: python3 -m unittest PhageScanner.tests.test_DNA

            - name: Test with tox
              run: tox

    ubuntu-testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.12'

            - name: Cache Python dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: run unit tests for DNA module
              run: python3 -m unittest PhageScanner.tests.test_DNA

            - name: Test with tox
              run: tox

